version: '3.9'

services:
  
  database:
    image: postgres:latest
    container_name: ft_database
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - inside

  # backend:
  #   container_name: ft_backend
  #   build: ./app-backend
  #   depends_on:
  #     - database
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - inside

  # frontend:
  #   container_name: ft_frontend
  #   build: ./app-frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - inside

volumes:
  database:

networks:
  inside: